### ISSUE TITLE
configuration bug

### ISSUE THREAD

**Issue by limelect** [groehner/guipy#3]
ver 1.0.1 Scroll in configuration all the way down
press tools>git
scroll bar disappears to receive it back use the keyboard up all the way.
go into editor then it comes back
Themes most are black I blue some white.
No real range.
Syntax color while scrolling in elements no change in "code sample"
I will keep playing.
I did not get an answer how do I get an EXECUTE program ??????

**Comment by groehner** [comment]
Hint 1:
ver 1.0.1 Scroll in configuration all the way down
press tools>git
scroll bar disappears to receive it back use the keyboard up all the way.
go into editor then it comes back

Answer: The scrollbar is only visible if needed, otherwise unvisible. It's needed, if the editor node is expanded. If the editor is close, you don't have a scrollbar.

Hint 2:
Themes most are black I blue some white.
No real range.

Answer: 
black and white based themes are usually used. If someone really want's  a red, green or blue based theme, it's possible to create it yourself. Look at c:\ProgramData\GuiPy\Highlighters 

Hint 3:
Syntax color while scrolling in elements no change in "code sample"

Answer: 
"color sample" shows the elements, therefore there are no changes.
To change something use Foreground/Background Color or Text attibutes

Hint 4:
I did not get an answer how do I get an EXECUTE program ??????

Answer:
My answer was in issue #1 No 2.

What exactly are you asking for? Is it this:
https://datatofish.com/executable-pyinstaller/
Perhaps it's possible to configure a new Tool (Menu Tools/Tools/Configure Tools)

I can add: at the moment GuiPy has no tool to create an executable
